spring:
  datasource:
    url: jdbc:mysql://localhost:8080/connect
    username: root
    password: passed1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Can be 'none', 'update', 'create', or 'create-drop'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
