server:
  port: 8010
spring:
  thymeleaf:
      enabled: true
      prefix: classpath:/templates/
      suffix: .html
      mode: HTML
      cache: false
  datasource:
    url: jdbc:mysql://localhost:8080/mydb?useSsl=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: passed1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Can be 'none', 'update', 'create', or 'create-drop'
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
config:
  threadsForSites: 5
  threadsForPages: 5
  maxPagesPerSite: 30
  indexingAvailable: true
  sites:
    - "https://www.svetlovka.ru"
    - "https://dimonvideo.ru"
    - "https://dombulgakova.ru"
    - "https://volochek.life"

